variables:
    SolutionBaseName: 'DFC.App.Pages'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio
    

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:

  - job: BuildTestAndAnalyze
    displayName: "Test & package ARM template(s)"
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - task: PublishPipelineArtifact@0
      displayName: Publish Page Registration artifact
      inputs:
        targetPath: '$(Build.SourcesDirectory)/Resources/PageRegistration'
        artifactName: ${{ variables.SolutionBaseName }}.PageRegistrations


  - job: BuildDotNetCore
    displayName: Build-DotNetCore

    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true
        TestSuffix: UnitTests
