variables:
  ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'
  SolutionBaseName: 'DFC.App.Pages'
  BuildPlatform: 'any cpu'
  BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

trigger: 
  branches:
    include: 
    - dev
    - master

pr:
  branches:
    include: 
    - dev
    - master
    

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:

  - job: BuildTestAndAnalyze
    displayName: "Test & package ARM template(s)"
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

    - task: PublishPipelineArtifact@0
      displayName: Publish Page Registration artifact
      inputs:
        targetPath: '$(Build.SourcesDirectory)/Resources/PageRegistration'
        artifactName: ${{ variables.SolutionBaseName }}.PageRegistrations

  - job: BuildDotNetCore
    displayName: Build-DotNetCore

    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true
        TestSuffix: UnitTests

- stage: DeployToDevAppPages
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV_AppPages
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-dev
  - template: VariableTemplates\DevEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV_AppPages
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      PathRegistrationApiUrl: "$(PathRegistrationApiUrl)"
      RegionRegistrationApiUrl: "$(RegionRegistrationApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)

- stage: DeployToDevDraftAppPages
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to DEV-DRAFT_AppPages
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: dfc-app-draft
  - group: dfc-app-shared-registration-draft
  - group: dfc-stax-shared-dev
  - template: VariableTemplates\DevDraftEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: DEV-DRAFT_AppPages
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      PathRegistrationApiUrl: "$(PathRegistrationApiUrl)"
      RegionRegistrationApiUrl: "$(RegionRegistrationApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)

- stage: DeployToSITAppPages
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT_AppPages
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: dfc-app-shared-registration
  - group: dfc-stax-shared-sit
  - template: VariableTemplates\SitEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT_AppPages
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      PathRegistrationApiUrl: "$(PathRegistrationApiUrl)"
      RegionRegistrationApiUrl: "$(RegionRegistrationApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)

- stage: DeployToSITDraftAppPages
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Deploy to SIT-DRAFT_AppPages
  variables:
  - group: dfc-shared-all
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: dfc-app-draft
  - group: dfc-app-shared-registration-draft
  - group: dfc-stax-shared-sit
  - template: VariableTemplates\SitDraftEnvironmentVariables.yml
  
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: $(ResourceGroup)
      DfCDevopsPath: '$(Agent.BuildDirectory)/s/dfc-devops'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      EnvironmentName: SIT-DRAFT_AppPages
      AppSharedResourceGroup: $(AppSharedResourceGroup)
      appSharedCosmosDBName: $(appSharedCosmosDBName)
      PageRegistrationPath: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.PageRegistrations/"
      PageRegistrationFile: "$(PageRegistrationFile)"
      PathRegistrationApiUrl: "$(PathRegistrationApiUrl)"
      RegionRegistrationApiUrl: "$(RegionRegistrationApiUrl)"
      ApimCompositeKey: "$(ApimCompositeKey)"
      AppServiceName: '$(AppServiceName)'
      AppRegistryClientOptionsBaseAddress: $(AppRegistryClientOptionsBaseAddress)