variables:
- name: ReleaseEnvironmentName
  value: DEV
- name: AppServiceName
  value: dfc-dev-app-pages-as
- name: cosmosDbCollectionName
  value: pages
- name: EnableAzureMonitorAlerting
  value: true
- name: EventGridSubscriptionModelEndpoint
  value: https://dfc-dev-app-pages-as.azurewebsites.net
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: dfc-dev-app-pages-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: ApimProductInstanceName
  value: Pages
- name: ApimProductId
  value: Pages
- name: ApimLoggerName
  value: Pages-logger
- name: ApiName
  value: Pages-API
- name: PageRegistrationFile
  value: registration.json