variables:
- name: ReleaseEnvironmentName
  value: DEV
- name: AppServiceName
  value: dfc-dev-app-pages-as
- name: cosmosDbCollectionName
  value: pages
- name: EnableAzureMonitorAlerting
  value: true
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/Pages
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: dfc-dev-app-pages-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-dev-app-pages-as.azurewebsites.net/api/pages
- name: ApplicationName
  value: DFC-App-Pages
- name: EventGridSubjectPrefix
  value: /dfc-app-pages/
- name: AppRegistryClientOptionsBaseAddress
  value: $(ApimProxyAddress)/composite-ui-appRegistry/pages/
- name: SummaryEndpoint
  value: /page
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: contentUrl
  value: https://dfc-dev-api-cont-fa.azurewebsites.net/api/execute
- name: subscriptionUrl
  value: https://dfc-dev-api-eventgridsubscriptions-fa.azurewebsites.net