variables:
- name: ReleaseEnvironmentName
  value: PP-DRAFT
- name: AppServiceName
  value: $(WebAppPrefix)-as-ver2
- name: AppServicePlanSuffix
  value: -migrated
- name: EnableAzureMonitorAlerting
  value: true
- name: pagesAppDatabaseThroughput
  value: 7500
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: DFC-App-Pages-draft
- name: SummaryEndpoint
  value: /page
- name: contentMode
  value: DRAFT
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: apiName
  value: pages-draft
- name: apiId
  value: composite-ui-pages-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-pp-draft-app-pages
- name: ExceptionCountThreshold
  value: 10
- name: Expiry
  value: 4