variables:
- name: ReleaseEnvironmentName
  value: PP
- name: AppServiceName
  value: dfc-pp-app-pages-as
- name: cosmosDbCollectionName
  value: pages
- name: EnableAzureMonitorAlerting
  value: true
- name: EventGridSubscriptionModelEndpoint
  value: https://dfc-pp-app-pages-as.azurewebsites.net
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: dfc-pp-app-pages-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-pp-app-pages-as.azurewebsites.net/api/pages
- name: ApplicationName
  value: DFC-App-Pages
- name: EventGridSubjectPrefix
  value: /dfc-app-pages/
- name: AppRegistryClientOptionsBaseAddress
  value: $(ApimProxyAddress)/composite-ui-appRegistry/pages/
- name: SummaryEndpoint
  value: content/getcontent/api/execute/page