variables:
- name: ReleaseEnvironmentName
  value: PRD
- name: AppServiceName
  value: dfc-prd-app-pages-as
- name: cosmosDbCollectionName
  value: pages
- name: EnableAzureMonitorAlerting
  value: true
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/pages
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: dfc-prd-app-pages-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-prd-app-pages-as.ase-01.dfc.prodazure.sfa.bis.gov.uk/api/pages
- name: ApplicationName
  value: DFC-App-Pages
- name: EventGridSubjectPrefix
  value: /dfc-app-pages/
- name: AppRegistryClientOptionsBaseAddress
  value: $(ApimProxyAddress)/composite-ui-appRegistry/pages/
- name: SummaryEndpoint
  value: /page
- name: aspTier
  value: Standard
- name: aspInstances
  value: 3
- name: aspSize
  value: 1
- name: contentUrl
  value: https://dfc-prd-api-cont-fa.ase-01.dfc.prodazure.sfa.bis.gov.uk/api/execute
- name: subscriptionUrl
  value: https://dfc-prd-api-eventgridsubscriptions-fa.ase-01.dfc.prodazure.sfa.bis.gov.uk
- name: apiName
  value: pages