variables:
- name: ReleaseEnvironmentName
  value: PRD
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: EnableAzureMonitorAlerting
  value: true
- name: pagesAppDatabaseThroughput
  value: 7500
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: ApplicationName
  value: DFC-App-Pages
- name: SummaryEndpoint
  value: /page
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: clientAffinity
  value: false
- name: contentMode
  value: PUBLISHED
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: apiName
  value: pages
- name: apiId
  value: composite-ui-pages
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-prd-app-pages
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75