variables:
- name: ReleaseEnvironmentName
  value: PRD
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: cosmosDbCollectionName
  value: $(apiName)
- name: EnableAzureMonitorAlerting
  value: true
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/pages
- name: pagesAppDatabaseThroughput
  value: 7500
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://$(AppServiceName).$(appServiceDomain)/api/pages
- name: ApplicationName
  value: DFC-App-Pages
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/
- name: AppRegistryClientOptionsBaseAddress
  value: $(ApimProxyAddress)/composite-ui-appRegistry/pages/
- name: SummaryEndpoint
  value: /page
- name: contentMode
  value: PUBLISHED
- name: contentUrl
  value: $(ContentApiAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-prd-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: apiName
  value: pages
- name: apiId
  value: composite-ui-pages
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-prd-app-pages
- name: ExceptionCountThreshold
  value: 10
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value:
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value: