variables:
- name: ReleaseEnvironmentName
  value: SIT-DRAFT
- name: AppServiceName
  value: dfc-sit-draft-app-pages-as
- name: cosmosDbCollectionName
  value: pages-draft
- name: EnableAzureMonitorAlerting
  value: true
- name: EventGridSubscriptionModelEndpoint
  value: https://dfc-sit-draft-app-pages-as.azurewebsites.net
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: dfc-sit-draft-app-pages-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-sit-draft-app-pages-as.azurewebsites.net/api/pages