variables:
- name: ReleaseEnvironmentName
  value: SIT-DRAFT
- name: AppServiceName
  value: dfc-sit-draft-app-pages-as
- name: cosmosDbCollectionName
  value: pages-draft
- name: EnableAzureMonitorAlerting
  value: true
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/Pages
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: dfc-sit-draft-app-pages-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://dfc-sit-draft-app-pages-as.azurewebsites.net/api/pages
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value: draft
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value: draft-discarded
- name: ApplicationName
  value: DFC-App-Pages-draft
- name: EventGridSubjectPrefix
  value: /dfc-app-pages-draft/
- name: AppRegistryClientOptionsBaseAddress
  value: $(ApimProxyAddress)/composite-ui-appRegistry-draft/pages/
- name: SummaryEndpoint
  value: /page
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: contentUrl
  value: https://dfc-sit-draft-api-cont-fa.azurewebsites.net/api/execute
- name: subscriptionUrl
  value: https://dfc-sit-api-eventgridsubscriptions-fa.azurewebsites.net