variables:
- name: ReleaseEnvironmentName
  value: SIT-DRAFT
- name: AppServiceName
  value: $(WebAppPrefix)-as
- name: cosmosDbCollectionName
  value: $(apiName)
- name: EnableAzureMonitorAlerting
  value: true
- name: SubscriptionSettingsEndpoint
  value: $(ApimProxyAddress)/composite-ui/pages-draft
- name: pagesAppDatabaseThroughput
  value: 400
- name: ResourceGroup
  value: $(WebAppPrefix)-rg
- name: WebAppProjectName
  value: DFC.App.Pages
- name: PageRegistrationFile
  value: registration.json
- name: EventGridPublishClientOptionsApiEndpoint
  value: https://$(AppServiceName).$(appServiceDomain)/api/pages
- name: SubscriptionSettingsFilterIncludeEventTypes3
  value: draft
- name: SubscriptionSettingsFilterIncludeEventTypes4
  value: draft-discarded
- name: ApplicationName
  value: DFC-App-Pages-draft
- name: EventGridSubjectPrefix
  value: /$(ApplicationName)/
- name: AppRegistryClientOptionsBaseAddress
  value: $(ApimProxyAddress)/composite-ui-appRegistry-draft/pages/
- name: SummaryEndpoint
  value: /page
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: clientAffinity
  value: false
- name: contentUrl
  value: $(ContentApiDraftAddress)/api/execute
- name: subscriptionUrl
  value: https://dfc-sit-api-eventgridsubscriptions-fa.$(appServiceDomain)
- name: apiName
  value: pages-draft
- name: apiId
  value: composite-ui-pages-draft
- name: applicationUrl
  value: https://$(AppServiceName).$(appServiceDomain)
- name: WebAppPrefix
  value: dfc-sit-draft-app-pages
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75